### ISSUE TITLE
Package for homebrew

### ISSUE THREAD

**Issue by mroth** [mroth/scmpuff#2]
This should be possible, so do this to make installation easier for mac users.  Need to look into some research as to how this is done w/r/t go toolchain and making sure binary bottles get poured.

**Comment by mroth** [comment]
I have a working formula for this now, but homebrew will frown upon us submitting it to the Library before we actually announce this project and have some users.

**Comment by hugovk** [comment]
It's been [announced](https://twitter.com/mroth/status/591267682026201089)! I'm using it!

**Comment by cbowns** [comment]
If you have a branch with a test formula, push it and comment it here; I've contributed a few formulae before and can help test it if you'd like.

**Comment by mroth** [comment]
@cbowns https://github.com/mroth/homebrew/commit/b6d30a29509add59b83d9719953109bb360bdeb7

The one thing I don't have it currently is the ability to pull `head`, I wanted to purposefully omit it unless I could override the VERSION field appropriately (which I currently do in the formula directly since the build script relies on being checked out from git, whereas normal versioned HB builds are extracted from zip.)

In any event, I suspect I also need a few more stars on this project before the maintainers are inclined to accept it.

**Comment by cbowns** [comment]
HEAD-only brews are handled in another project from them (https://github.com/Homebrew/homebrew-head-only) and kinda frowned upon. (Apologies if you knew about this already.)

I thought homebrew also did tag-based checkouts from a `git` repo, have they moved away from those?

(The `go` build dependency is a bit of a drag.)

**Comment by cbowns** [comment]
Here's my build-time error. Most likely because of my lack of `go` configuration:

```
==> Downloading https://github.com/mroth/scmpuff/archive/v0.1.0.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; Mac OS X 10.10.3) https://github.com/mroth/scmpuff/archive/v0.1.0.tar.gz -C 0 -o /Library/Caches/Homebrew/scmpuff-0.1.0.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   121    0   121    0     0    220      0 --:--:-- --:--:-- --:--:--   220
  0     0    0 63582    0     0  30098      0 --:--:--  0:00:02 --:--:--   98k
==> Verifying scmpuff-0.1.0.tar.gz checksum
tar xf /Library/Caches/Homebrew/scmpuff-0.1.0.tar.gz
==> go build -o bin/scmpuff -ldflags '-X main.VERSION 0.1.0'
main.go:6:2: cannot find package "github.com/mroth/scmpuff/commands/expand" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/mroth/scmpuff/commands/expand (from $GOROOT)
	($GOPATH not set)
main.go:7:2: cannot find package "github.com/mroth/scmpuff/commands/inits" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/mroth/scmpuff/commands/inits (from $GOROOT)
	($GOPATH not set)
main.go:8:2: cannot find package "github.com/mroth/scmpuff/commands/status" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/mroth/scmpuff/commands/status (from $GOROOT)
	($GOPATH not set)
intro.go:6:2: cannot find package "github.com/mroth/scmpuff/vendor/_nuts/github.com/spf13/cobra" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/mroth/scmpuff/vendor/_nuts/github.com/spf13/cobra (from $GOROOT)
	($GOPATH not set)
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
```

**Comment by mroth** [comment]
@cbowns Hmm interesting.  

I believe Go gets installed here since its specified as a dependency (which shouldn't be a big problem because bottles will get automatically made for people). So the compilation issue here results in not having a `$GOPATH` set, which is an annoyance of Go certainly.  Let me dig into this.

(BTW, I didn't mean making it head-only, merely providing a head option.  But to do that correctly with my build variables I need to be able to have conditional logic for compiling differently in that situation.)

**Comment by mroth** [comment]
@cbowns Okay I just pushed a change in mroth/homebrew@f11e82b that I think might address this.  Can you try and let me know if it fixes compilation for you?

**Comment by cbowns** [comment]
Yeah, the `go` bottle was pretty straightforward.

**Comment by cbowns** [comment]
It still falls over:

```
cbowns at Atlas in ~ ☆
% ○ brew install --debug --verbose https://raw.githubusercontent.com/mroth/homebrew/f11e82b6b3e30c6ec5ad2046b178d5f80a4f8232/Library/Formula/scmpuff.rb          2015-05-0 [09:52:17]
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; Mac OS X 10.10.3) https://raw.githubusercontent.com/mroth/homebrew/f11e82b6b3e30c6ec5ad2046b178d5f80a4f8232/Library/Formula/scmpuff.rb -o /Library/Caches/Homebrew/Formula/scmpuff.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   542  100   542    0     0   1415      0 --:--:-- --:--:-- --:--:--  1418
/usr/local/Library/brew.rb (Formulary::FromUrlLoader): loading /Library/Caches/Homebrew/Formula/scmpuff.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/go.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /Library/Caches/Homebrew/Formula/scmpuff.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/go.rb
==> Downloading https://github.com/mroth/scmpuff/archive/v0.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/scmpuff-0.1.0.tar.gz
==> Verifying scmpuff-0.1.0.tar.gz checksum
tar xf /Library/Caches/Homebrew/scmpuff-0.1.0.tar.gz
==> go build -o bin/scmpuff -ldflags '-X main.VERSION 0.1.0'
main.go:6:2: cannot find package "github.com/mroth/scmpuff/commands/expand" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/mroth/scmpuff/commands/expand (from $GOROOT)
	/private/tmp/scmpuff20150501-67713-hkqs72/scmpuff-0.1.0/src/github.com/mroth/scmpuff/commands/expand (from $GOPATH)
main.go:7:2: cannot find package "github.com/mroth/scmpuff/commands/inits" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/mroth/scmpuff/commands/inits (from $GOROOT)
	/private/tmp/scmpuff20150501-67713-hkqs72/scmpuff-0.1.0/src/github.com/mroth/scmpuff/commands/inits (from $GOPATH)
main.go:8:2: cannot find package "github.com/mroth/scmpuff/commands/status" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/mroth/scmpuff/commands/status (from $GOROOT)
	/private/tmp/scmpuff20150501-67713-hkqs72/scmpuff-0.1.0/src/github.com/mroth/scmpuff/commands/status (from $GOPATH)
intro.go:6:2: cannot find package "github.com/mroth/scmpuff/vendor/_nuts/github.com/spf13/cobra" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/mroth/scmpuff/vendor/_nuts/github.com/spf13/cobra (from $GOROOT)
	/private/tmp/scmpuff20150501-67713-hkqs72/scmpuff-0.1.0/src/github.com/mroth/scmpuff/vendor/_nuts/github.com/spf13/cobra (from $GOPATH)
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: go build -o bin/scmpuff -ldflags '-X main.VERSION 0.1.0' 
```

**Comment by cbowns** [comment]
The `scmpuff` commands it expects are (expectedly), not in my `go` directories.

```
% ○ brew list go                                                                                                                                                 2015-05-0 [09:56:04]
/usr/local/Cellar/go/1.4.2/bin/go
/usr/local/Cellar/go/1.4.2/bin/godoc
/usr/local/Cellar/go/1.4.2/bin/gofmt
/usr/local/Cellar/go/1.4.2/libexec/api/ (8 files)
/usr/local/Cellar/go/1.4.2/libexec/bin/ (3 files)
/usr/local/Cellar/go/1.4.2/libexec/doc/ (152 files)
/usr/local/Cellar/go/1.4.2/libexec/include/ (19 files)
/usr/local/Cellar/go/1.4.2/libexec/lib/ (3 files)
/usr/local/Cellar/go/1.4.2/libexec/misc/ (193 files)
/usr/local/Cellar/go/1.4.2/libexec/pkg/ (166 files)
/usr/local/Cellar/go/1.4.2/libexec/src/ (2759 files)
/usr/local/Cellar/go/1.4.2/libexec/test/ (1254 files)
/usr/local/Cellar/go/1.4.2/libexec/ (8 files)
```

```
% ○ find /usr/local/Cellar/go/1.4.2/libexec/src/ | grep -i mroth      

cbowns at Atlas in ~ ☃
% ○ echo $?                                                           
1
```

Nor is it in the temporary source directory:

```
cbowns at Atlas in /private/tmp/scmpuff20150501-67713-hkqs72/scmpuff-0.1.0 ☃
% ○ ll /private/tmp/scmpuff20150501-67713-hkqs72/scmpuff-0.1.0/src/                                   
ls: /private/tmp/scmpuff20150501-67713-hkqs72/scmpuff-0.1.0/src/: No such file or directory

cbowns at Atlas in /private/tmp/scmpuff20150501-67713-hkqs72/scmpuff-0.1.0 ☃
% ○ ll /private/tmp/scmpuff20150501-67713-hkqs72/scmpuff-0.1.0/                                       
total 96
0 drwxr-xr-x   3 cbowns  wheel   102B Apr 22 18:54 vendor/
0 drwxr-xr-x   7 cbowns  wheel   238B Apr 22 18:54 script/
8 -rw-r--r--   1 cbowns  wheel   1.0K Apr 22 18:54 main.go
8 -rw-r--r--   1 cbowns  wheel   1.5K Apr 22 18:54 intro.go
0 drwxr-xr-x  10 cbowns  wheel   340B Apr 22 18:54 features/
0 drwxr-xr-x   5 cbowns  wheel   170B Apr 22 18:54 commands/
8 -rw-r--r--   1 cbowns  wheel   1.4K Apr 22 18:54 Rakefile
8 -rw-r--r--   1 cbowns  wheel   4.0K Apr 22 18:54 README.md
8 -rw-r--r--   1 cbowns  wheel   239B Apr 22 18:54 Nut.toml
8 -rw-r--r--   1 cbowns  wheel   156B Apr 22 18:54 INSTALL.txt
8 -rw-r--r--   1 cbowns  wheel   109B Apr 22 18:54 Gemfile
8 -rw-r--r--   1 cbowns  wheel   1.3K Apr 22 18:54 CHANGELOG.md
8 -rw-r--r--   1 cbowns  wheel   534B Apr 22 18:54 .travis.yml
8 -rw-r--r--   1 cbowns  wheel   145B Apr 22 18:54 .goxc.json
8 -rw-r--r--   1 cbowns  wheel    46B Apr 22 18:54 .gitignore
8 -rw-r--r--   1 cbowns  wheel   370B Apr 22 18:54 .editorconfig
0 drwxr-xr-x  18 cbowns  wheel   612B Apr 22 18:54 ./
0 drwx------   3 cbowns  wheel   102B May  1 09:52 ../
```

**Comment by cbowns** [comment]
And one final "of note" bit:

This package:
```
    intro.go:6:2: cannot find package "github.com/mroth/scmpuff/vendor/_nuts/github.com/spf13/cobra" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/mroth/scmpuff/vendor/_nuts/github.com/spf13/cobra (from $GOROOT)
	/private/tmp/scmpuff20150501-72830-1od92ml/scmpuff-0.1.0/src/github.com/mroth/scmpuff/vendor/_nuts/github.com/spf13/cobra (from $GOPATH)
```


Is at a different path than the one above. Here's where I found it:

```
cbowns at Atlas in /private/tmp/scmpuff20150501-72830-1od92ml/scmpuff-0.1.0 ☆
% ○ ls /private/tmp/scmpuff20150501-72830-1od92ml/scmpuff-0.1.0/vendor/_nuts/github.com/spf13/cobra/                                                            2015-05-01 [10:15:58]
./			.gitignore		LICENSE.txt		cobra.go		command.go
../			.travis.yml		README.md		cobra_test.go		command_test.go
```

**Comment by mroth** [comment]
Yargh.  All the packages are local -- either vendored, or for most of them, they are actually just sub-directory packages.  I'm not sure how to configure the `$GOPATH` to allow this to be built locally in an arbitrary directory. It _should_ be simple but something is escaping me here.  I may need to ping someone who understands the weirdness of Go import paths better.

**Comment by mroth** [comment]
Okay, I think I finally have a working version of this.  @cbowns, try building the version I just put in my own tap: `brew install mroth/formulas/scmpuff`.

**Comment by mieky** [comment]
@mroth, just tested and installed perfectly from your tap on the first try. :+1:

**Comment by mroth** [comment]
Homebrew support is now [official](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/scmpuff.rb) in homebrew main, so closing this issue! :cake:
